### ISSUE TITLE
Span Extraction Evaluation

### ISSUE THREAD

**Issue by Shikib** [PolyAI-LDN/task-specific-datasets#7]
I'm running experiments on the DSTC8/Restaurant8k datasets you've provided, but I'm not clear on how exactly you do evaluation. I understand that you're doing macro averaged F-1 on predicted spans, but it's unclear how you deal with utterances with no slots. Would you be willing to share your evaluation script to ensure consistent evaluation? If not, any information you can provide regarding the evaluation methodology would be greatly appreciated.

Thank you!

**Comment by coopie** [comment]
Hi @Shikib - thanks for raising this!

For calculation of precision and recall, we do the following for each slot.

`precision = (number of correctly predicted examples with spans)/(all examples with a span predicted)`

`recall = (number of correctly predicted examples with spans)/(all examples with a span label)`

So in this case, an example with no label would contribute to precision if the model erroneously predicts a span for that example.

Hope this clears things up! We are all a bit busy here at the moment, otherwise I'd be happy to refactor/open-source the eval code we have.

**Comment by Shikib** [comment]
Thanks for clarifying Sam, a few follow-up questions.

1. You say "we do the following for each slot", are you computing the precision/recall/f1 for each slot type and then macro averaging? Or micro averaging?

2. It's unclear to me what you mean by "correctly predicted example". If there are multiple spans in a single utterance, is it marked as correct only if everything is correct?  

Since natural language is ambiguous, I wrote the following code snippet based on my interpretation of your answer. Could you please confirm that it's doing the right thing?

```
true = [ [("time", 1, 10)] , [("time", 1, 10), ("people", 12, 14)]  ... ]
pred = [ [("time", 1, 10)] , [("time", 1, 10), ("people", 12, 15)] ... ] 
slot_types [ "time", "people"]
slot_type_f1_scores = []

for slot_type in slot_types:
  tp, fp, fn = 0,0,0
  for t,p in zip(true, pred):
    true_spans = [e for e in t if e[0] == slot_type]
    pred_spans = [e for e in p if e[0] == slot_type]
    if len(true_spans) > 0 and true_spans == pred_spans:
      tp += 1
    else:
      if len(pred_spans) > 0:
        fp += 1
      if len(true_spans) > 0:
        fn += 1  
 
  precision = tp/(tp+fp)
  recall = tp/(tp+fn)
  f1_score = 2*precision*recall/(precision+recall)
  slot_type_f1_scores.append(f1_score)

overall_f1 = np.mean(slot_type_f1_scores)
```

Thank you!

**Comment by coopie** [comment]
Thanks for sharing your code, I tried to edit it to how we calculated the F1. 

(I did it all using vanilla lists - it's much cleaner using numpy but a little harder to grok)

```python3

true = [ [("time", 1, 10)] , [("time", 1, 10), ("people", 12, 15)]]
pred = [ [("time", 1, 10)] , [("time", 1, 9), ("people", 12, 15)]]
slot_types = [ "time", "people"]
slot_type_f1_scores = []

import numpy as np

for slot_type in slot_types:
    predictions_for_slot = [
        [p for p in prediction if p[0] == slot_type] for prediction in pred
    ]
    labels_for_slot = [
        [l for l in label if l[0] == slot_type] for label in true
    ]

    proposal_made = [len(p) > 0 for p in predictions_for_slot]
    has_label = [len(l) > 0 for l in labels_for_slot]
    prediction_correct = [
        prediction == label for prediction, label in zip(predictions_for_slots, labels_for_slots)
    ]

    true_positives = sum([
        int(proposed and correct)
        for proposed, correct in zip(proposal_made, prediction_correct)
    ])
    num_predicted = sum([int(proposed) for proposed in proposal_made])
    num_to_recall = sum([int(hl) for hl in has_label])

    precision = true_positives / (1e-5 + num_predicted)
    recall = true_positives / (1e-5 + num_to_recall)

    f1_score = 2 * precision * recall / (1e-5 + precision + recall)
    slot_type_f1_scores.append(f1_score)

    print(f'scores for {slot_type}:')
    print(f'precision:{precision}:')
    print(f'recall:{recall}:')
    print(f'f1_score:{f1_score}:')
    print('=====\n')

overall_f1 = np.mean(slot_type_f1_scores)

print(f'mean f1: {overall_f1}')
```

should print:
```
scores for time:
precision:0.49999750001249993:
recall:0.49999750001249993:
f1_score:0.49999250006249973:
=====

scores for people:
precision:0.0:
recall:0.0:
f1_score:0.0:
=====

mean f1: 0.24999625003124987
```

**Comment by Shikib** [comment]
Thank you so much Sam! This is really helpful.

**Comment by Shikib** [comment]
Sorry for bugging you so much about this, I promise this is the last question.

Just wanted to clarify that in the code you posted above, should `prediction_correct = [prediction == label for prediction, label in zip(pred, true)]` be `prediction_correct = [prediction == label for prediction, label in zip(predictions_for_slots, labels_for_slots)]` instead?

And the output should be:

```
scores for time:
precision:0.49999750001249993:
recall:0.49999750001249993:
f1_score:0.49999250006249973:
=====

scores for people:
precision:0.9999900000999989:
recall:0.9999900000999989:
f1_score:0.9999850001249991:
=====

mean f1: 0.7499887500937494
```

Or is it intentional that the F-1 score for `people` is penalized even though it was never mis-predicted?

**Comment by coopie** [comment]
@Shikib yes you are correct, I'll update my comment above so no one esle has that mistake

**Comment by Shikib** [comment]
Thanks Sam! Closing this issue.
